# Infrastructure
flexicore.entities=/home/flexicore/entities
flexicore.plugins=/home/flexicore/plugins
flexicore.externalStatic=/home/flexicore/ui/
flexicore.internalStaticLocation=file:/home/flexicore/ui-swagger/
##flexicore.swagger.url=https://api.playground.wizzdi.com
flexicore.flyway.enable=false
flexicore.api.path=
api.prefix=
cors.enabled=true

# Logging
logging.file.name=/var/log/flexicore/flexicore.log
logging.config=file:/home/flexicore/config/logback-spring.xml

# Database & Performance
spring.datasource.hikari.maximum-pool-size=200
basic.iot.mqtt.jdbcRatio=0.405
rules.jdbcRatio=0.045
eclipselink.cache.shared.default=false

# Basic IoT Core
basic.iot.id=playground
basic.iot.keyPath=/home/flexicore/certs/server-key.pem


# Basic IoT Logic & FOTA
basic.iot.fota.baseUrl=https://playground.wizzdi.com/fota/downloadFirmware/
basic.iot.connectivityCheckInterval=450000
basic.iot.connectivityDelayInterval=120000
basic.iot.lastSeenThreshold=900000
basic.iot.firmware.update.reminderInterval=1200000
basic.iot.fixInvalidStatusCron=0 10 7 * * *

# Integrations (SendGrid)
wizzdi.flexicore.sendgrid.dynamicInvokers.apiKey=
wizzdi.maps.status.sendgrid.from=info@playground.wizzdi.com
wizzdi.maps.status.sendgrid.template.id=
