# Infrastructure
flexicore.entities=/home/flexicore/entities
flexicore.plugins=/home/flexicore/plugins
flexicore.externalStatic=/home/flexicore/ui/
flexicore.internalStaticLocation=file:/home/flexicore/ui-swagger/
##flexicore.swagger.url=https://api.playground.wizzdi.com
flexicore.flyway.enable=false
flexicore.api.path=
api.prefix=
cors.enabled=true

# Logging
logging.file.name=/var/log/flexicore/flexicore.log
logging.config=file:/home/flexicore/config/logback-spring.xml

# Database & Performance
spring.datasource.hikari.maximum-pool-size=200
rules.jdbcRatio=0.045
eclipselink.cache.shared.default=false

# Basic IoT Logic & FOTA
basic.iot.id=playground
# This key is used for application-level message signing (RSA PKCS#8)
basic.iot.keyPath=/home/flexicore/certs/server-signing-key.pem
basic.iot.fota.baseUrl=https://playground.wizzdi.com/fota/downloadFirmware/
basic.iot.connectivityCheckInterval=450000
basic.iot.connectivityDelayInterval=120000
basic.iot.lastSeenThreshold=900000
basic.iot.firmware.update.reminderInterval=1200000
basic.iot.fixInvalidStatusCron=0 10 7 * * *

# MQTT Infrastructure
basic.iot.mqtt.enabled=false
basic.iot.start.delay=30
basic.iot.mqtt.url=ssl://localhost:8883
basic.iot.mqtt.certsBaseDir=/home/flexicore/mqttcerts
basic.iot.mqtt.trustStore=/home/flexicore/mqttcerts/truststore.jks
basic.iot.mqtt.trustStorePassword=password
basic.iot.mqtt.trustStoreType=JKS
# These keys/certs are used for transport-level TLS connection to the MQTT broker
basic.iot.mqtt.jdbcRatio=0.405

# Integrations (SendGrid)
wizzdi.flexicore.sendgrid.dynamicInvokers.apiKey=
wizzdi.maps.status.sendgrid.from=info@playground.wizzdi.com
wizzdi.maps.status.sendgrid.template.id=
