package com.wizzdi.basic.iot.model;

public enum FleetHealthMetricType {
    MEMBER_COUNT,
    OFFLINE_COUNT,
    OFFLINE_PERCENT,
    STALE_COUNT,
    STALE_PERCENT,
    SEVERITY_AT_OR_ABOVE_COUNT,
    SEVERITY_AT_OR_ABOVE_PERCENT,
    WEIGHTED_SEVERITY_AVERAGE,
    REQUIRED_UNHEALTHY_COUNT,
    HUMAN_INTERVENTION_COUNT,
    HUMAN_INTERVENTION_PERCENT,
    UNKNOWN_SEVERITY_COUNT,
    UNKNOWN_SEVERITY_PERCENT
}
